spring.application.name=GatewayMS
server.port=9000
#User Ms
spring.cloud.gateway.routes[0].id=userMS
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**